### ISSUE TITLE
use this model to noise reduction

### ISSUE THREAD

**Issue by xxoospring** [JusperLee/Dual-Path-RNN-Pytorch#15]
I used this project for noise reduction, this was what I got, Its really amazing!!! Thanks for your implement.
|-samples
    |-mix: mixture audio (clean speech + noise)
    |-speech-actual: clean audio
    |-speech-separated: separated audio

all the audios are from test set.
[samples.zip](https://github.com/JusperLee/Dual-Path-RNN-Pytorch/files/4947540/samples.zip)

**Comment by JusperLee** [comment]
Thank you for your evaluation of this repository and keep in touch.

**Comment by zxj329** [comment]
您好，我想问下您，您是用的多少张卡，每张卡多少batch_size，以及前几代你的loss大概是多少，我一直loss在17左右，我觉得应该是负数呀。
