### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Conv_TasNet:         Missing key(s) in state_dict: "separation.conv1d_list.0.0.conv1x1.weight",

### ISSUE THREAD

**Issue by Yunlong-He** [JusperLee/Dual-Path-RNN-Pytorch#18]
When I run inference with provided model, I got following error, is there anything wrong in the model?
============================================================
root:/lab/Dual-Path-RNN-Pytorch# python3 test_tasnet.py  -mix_scp=sample/test.scp -save_path=sample/result   
Traceback (most recent call last):
  File "test_tasnet.py", line 81, in <module>
    main()
  File "test_tasnet.py", line 76, in main
    separation=Separation(args.mix_scp, args.yaml, args.model, gpuid)
  File "test_tasnet.py", line 20, in __init__
    net.load_state_dict(dicts["model_state_dict"])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Conv_TasNet:
        Missing key(s) in state_dict: "separation.conv1d_list.0.0.conv1x1.weight", "separation.conv1d_list.0.0.conv1x1.bias", "separation.conv1d_list.0.0.PReLu1.weight", "separation.conv1d_list.0.0.norm1.weight", "separation.conv1d_list.0.0.norm1.bias", "separation.conv1d_list.0.0.dwconv.weight", "separation.conv1d_list.0.0.dwconv.bias", "separation.conv1d_list.0.0.PReLu2.weight", "separation.conv1d_list.0.0.norm2.weight", "separation.conv1d_list.0.0.norm2.bias", "separation.conv1d_list.0.0.end_conv1x1.weight", "separation.conv1d_list.0.0.end_conv1x1.bias", "separation.conv1d_list.0.1.conv1x1.weight", "separation.conv1d_list.0.1.conv1x1.bias", "separation.conv1d_list.0.1.PReLu1.weight", "separation.conv1d_list.0.1.norm1.weight", "separation.conv1d_list.0.1.norm1.bias", "separation.conv1d_list.0.1.dwconv.weight", "separation.conv1d_list.0.1.dwconv.bias", "separation.conv1d_list.0.1.PReLu2.weight", "separation.conv1d_list.0.1.norm2.weight", "separation.conv1d_list.0.1.norm2.bias", "separation.conv1d_list.0.1.end_conv1x1.weight", "separation.conv1d_list.

**Comment by Yunlong-He** [comment]
Yes, I downloaded the model from link of the repo:
root@neufoundry-test-gpu-host14:/lab/github/speech/Dual-Path-RNN-Pytorch# ls ./checkpoint/Conv_Tasnet_skip/best.pt -l
-rw-r--r-- 1 root root 60796676 Aug 21 09:48 ./checkpoint/Conv_Tasnet_skip/best.pt

**Comment by JusperLee** [comment]
If you want to use the Conv-TasNet model, I recommend you to use this repository: https://github.com/JusperLee/Conv-TasNet

**Comment by JusperLee** [comment]
Maybe the model file stored in my repository does not match model.py, causing the error.

**Comment by Yunlong-He** [comment]
I tried https://github.com/JusperLee/Conv-TasNet, but got same error, I searched in google, someone said that error may be related to nn.DataParallel,  but I don't see such code in your training file, so there may be other reasons.  

could you help to confirm whether you generated the best.pt by yourself?  and what pytorch version are you using? Thanks

**Comment by JusperLee** [comment]
Your error is that the structure of the saved model is different from the structure of model.py.

**Comment by Yunlong-He** [comment]
Thanks, I just found another model file which is usable, though it is from another project, but I think the root cause is just as JusperLee said, thanks to JusperLee,👍
