### ISSUE TITLE
你好，昨天听了你的意见我在知乎上看到了你有关dual-path RNN的论文解读，于是想尝试看看这篇文章的复现代码的指标性能能达到多少，对这里面的SDRi指标仍旧有不明白的地方

### ISSUE THREAD

**Issue by Jasonheartesyu** [JusperLee/Dual-Path-RNN-Pytorch#2]
现在因为疫情原因不能返校，目前只有一台1050的笔记本，想请教下能跑得动这个的训练代码吗？以及在该文章中的SDRi指标如何与Google的SDR进行比较，是否可以对SDRi这样理解，纯净语音与嘈杂环境的信号失真比得到一个SDR1，纯净语音信号与生成的目标语音信号的失真比得到SDR2，然后SDR2与SDR1的对数关系比得到SDRi？

**Comment by JusperLee** [comment]
SI-SNR其实就是SDR的计算方式，只不过他们在论文里面重新定义了一下。具体的内容在"Single-Channel Multi-Speaker Separation using Deep Clustering"这篇文章中有所提及，后面的文章均是使用该说法。我这个代码的内存并不是很大，我自己跑的话1个batch size，大概需要7355M, 11G的显存就可以了。下面的图片为SI-SNR计算方法，和文章中提及更改的内容，仅供参考。
![image](https://user-images.githubusercontent.com/33806018/75103852-ea2b8000-563b-11ea-985b-751524d9dd86.png)

![image](https://user-images.githubusercontent.com/33806018/75103860-1cd57880-563c-11ea-9766-190c603df69d.png)

**Comment by Jasonheartesyu** [comment]
你好，你说的SI-SNR就是SDR的计算方式，是否指的是SI-SNR是SDRi的计算方式。在dual-path rnn文章中是SDRi是这样介绍这个指标，The degree of improvement in the signal ﬁdelity is measured by signal-to-distortion ratio improvement(SDRi)，这应该和SDR还是不一样的吧。

**Comment by JusperLee** [comment]
不好意思我刚才的说法是不正确的，没有仔细check你的问题，所以我把那条comment删除了。Google的SDR和Rual-path-RNN的SDRi是一样的计算方式。因为在Google的文章中也提到了SDR improvement，这个应该是一种SDR的说法，即就是SDR改善的意思，应该还是SDR的计算方式，只是说法上的差别。下面是Google在文章中所提及的SDRi内容。

![image](https://user-images.githubusercontent.com/33806018/75104144-62944000-5640-11ea-9639-63244c87d2dd.png)
![image](https://user-images.githubusercontent.com/33806018/75104167-a8510880-5640-11ea-8286-00597888420a.png)

其中Google和Deep Clustering均引用了2006年提出的语音分离的评价指标论文“Performance Measurement in Blind Audio Source Separation.”，该文章中也对SDR进行了说明。如下为SDR的计算方式。

![image](https://user-images.githubusercontent.com/33806018/75104189-f7973900-5640-11ea-9a00-728603d34e49.png)

综上考虑，我认为SDR improvement（SDRi）和SDR的计算方式一致。

**Comment by Jasonheartesyu** [comment]
你好，抱歉，我没有仔细查看google中对于SDR指标的解释，的确应该如你所述。这样看的话，dual-path RNN纯语音分离的方法在特定数据集上的双人混合语音分离效果能达到19dB比谷歌的视听语音分离中双人语音分离的10.3dB效果高出8.7dB，是否直接表明了dual-path RNN方法的相比于谷歌语音分离方法具有更大的优越性？

**Comment by JusperLee** [comment]
也不好证明，因为他们两个的数据集不一致，所以无法证明优越性。但是就纯语音方法，Dual-Path-RNN还是很优越的语音分离方法

**Comment by Jasonheartesyu** [comment]
嗯嗯，明白，谢谢你能耐心帮我解答问题，十分感谢！！！
