### ISSUE TITLE
Dual-Path的epoch

### ISSUE THREAD

**Issue by fanmanqian** [JusperLee/Dual-Path-RNN-Pytorch#22]
作者您好，在您的代码里Dual-Path被设置成了单块gpu运行，如果运行100epoch，我这边的数据量要3个月，这里的epoch如果自己设置的小一点 会有效果么？最小的话 大概设成多少？

**Comment by JusperLee** [comment]
你好，在50epoch能够达到17.0 db左右

**Comment by fanmanqian** [comment]
好哒，谢谢您~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kai Li (李凯)"<notifications@github.com&gt;; 
发送时间: 2020年10月15日(星期四) 下午2:32
收件人: "JusperLee/Dual-Path-RNN-Pytorch"<Dual-Path-RNN-Pytorch@noreply.github.com&gt;; 
抄送: "孟凡满"<2563965485@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [JusperLee/Dual-Path-RNN-Pytorch] Dual-Path的epoch (#22)





 
你好，在50epoch能够达到17.0 db左右
