### ISSUE TITLE
PESQ

### ISSUE THREAD

**Issue by fanmanqian** [JusperLee/Dual-Path-RNN-Pytorch#24]
作者，您好，Dual path的效果SDR很高13.多，听的也很清楚，但是计算pesq和stoi值的时候很低，pesq只有1.9左右，这个可能是什么问题呢？

**Comment by JusperLee** [comment]
pesq和stoi属于听感上的评价指标，因为这些模型生成的音频的高频都有所缺失，所以在变化的时候都会变的较差。

**Comment by fanmanqian** [comment]
好的，谢谢您～


 
---Original---
