### ISSUE TITLE
Evaluation on 4sec segments? 

### ISSUE THREAD

**Issue by mpariente** [JusperLee/Dual-Path-RNN-Pytorch#3]
Hi, 

I was just having a look at the evaluation script. 
Can you confirm that you are discarding the utterances smaller than 2s and chunking all remaining utterances in chunks of 4sec, zero-padding the last chunk? 

Thanks

BTW, the demo page is great !

**Comment by JusperLee** [comment]
The reason why I deleted the audio less than 2s is that when training,
using long speech fragments can learn better separation features.  During
the test, the audio is not processed, which means that it contains the
audio less than 2s and all other audio in the test data set.

Pariente Manuel <notifications@github.com>于2020年4月16日 周四下午11:15写道：

**Comment by mpariente** [comment]
Thanks for your answer. 
For training, I understand the reason but it looks like you do the same at test time [here](https://github.com/JusperLee/Dual-Path-RNN-Pytorch/blob/master/dualrnn_test.py#L16) because the default behavior of `AudioReader` discard 2s signals and splits into 4sec the rest. 

Please explain me where I'm mistaken ^^

**Comment by JusperLee** [comment]
I'm sorry this is my error, I will update the evaluation code immediately. Evaluation is for all lengths of audio.

**Comment by JusperLee** [comment]
[fix test bug](https://github.com/JusperLee/Dual-Path-RNN-Pytorch/commit/b7544a31effe875104aff0fb65d226f15f47a05b)

**Comment by mpariente** [comment]
Thanks for the update !
