### ISSUE TITLE
About computing loss -SI-SNR

### ISSUE THREAD

**Issue by Reid-Cui7** [JusperLee/Dual-Path-RNN-Pytorch#32]
Thank you for your great work in Speech Separation, I've been benifited a lot from your awesome-speech-separation repository.
I am a little confused when computing loss:
In model->loss.py->function sisnr(): you return 20*log10(...）at last, but when computing Si-SNR, we should use 10*log10(...), should we ?
I can achieve about 19 in Si-SNR according to your code, but if I change to 10, the result falls

**Comment by JusperLee** [comment]
if you look the sisnr equation, you will find this equation: 10log()^2=20log()

**Comment by Reid-Cui7** [comment]
OH,  man! How silly I am, I just focus on the factor, did not get into it.
Thanks for your patience
