### ISSUE TITLE
计算 loss -SI-SNR

### ISSUE THREAD

**Issue by rongannn** [JusperLee/Dual-Path-RNN-Pytorch#45]
您好，之前看您解答问题的时候说DPRNN在50个epoch的时候可以到达17dB左右，但是我现在运行了36个epoch，才到14.7dB，您知道这是什么原因吗？
![image](https://user-images.githubusercontent.com/37686004/160992914-cbedb486-cfc5-40b2-8d66-d71da31e2674.png)
是我使用的WSJ0数据集太大的原因吗？

**Comment by JusperLee** [comment]
可以改一下lr试试，或者超参数和论文保持一致

**Comment by rongannn** [comment]
是将学习率降低一半吗，还有我看您的代码中的参数是和论文中的一致的啊

**Comment by rongannn** [comment]
> 可以改一下lr试试，或者超参数和论文保持一致

是将学习率降低一半吗，还有我看您的代码中的参数是和论文中的一致的啊

**Comment by rongannn** [comment]
我还想问一下，您获得的wsj0_2mix数据集有多少啊，我现在使用的WSJ0-2mix数据集有20000个训练集，5000个验证集以及3000个测试集。

**Comment by JusperLee** [comment]
一样的。那你可以检查一下超参数设置

**Comment by rongannn** [comment]
好的，那我试一试，谢谢您
