### ISSUE TITLE
Batch size of DPRNN_TasNet

### ISSUE THREAD

**Issue by lijie03** [JusperLee/Dual-Path-RNN-Pytorch#5]
Hi Kai,

I noticed that the bachsize in your training config of DPRNN_TasNet is 1. Have you tried larger batchsize? How is the performance compared with batchsize 1?

Thanks a lot!

**Comment by JusperLee** [comment]
I have compared the larger batch size settings, but through comparison, I found that the smaller the batch size is, the better the result is when using rnn. I haven't found a corresponding explanation for this problem so far.
