### ISSUE TITLE
train_rnn.py error in make_dataloader(opt)

### ISSUE THREAD

**Issue by MrRfifa** [JusperLee/Dual-Path-RNN-Pytorch#51]
![image](https://user-images.githubusercontent.com/101003527/204133431-337754a4-dfb5-4f5b-bdc6-091874b79a9f.png)

**Comment by MrRfifa** [comment]
in create_scp.py by what should I change those files?
![image](https://user-images.githubusercontent.com/101003527/204133943-34df9c5f-7999-459d-83f0-1fd5b4fa5809.png)

**Comment by JusperLee** [comment]
If you are using the wsj0 dataset, you will need to change these paths to your own folder similar to this one.

**Comment by MrRfifa** [comment]
Help please!
![image](https://user-images.githubusercontent.com/101003527/205490770-04fbb9aa-3325-4fa1-a4cc-0aebbcba889b.png)
