### ISSUE TITLE
关于使用预训练模型的报错

### ISSUE THREAD

**Issue by PANPANKK** [JusperLee/Dual-Path-RNN-Pytorch#52]
下载了demo语音，配置好了预训练文件，运行dualrnn_test_wav.py出现如下错误；想问下这是什么情况，求答复（本人新手入门，觉得这个项目挺好的，想着先运行下看看效果，谢谢了，万分感激！！！！）
ValueError: Expected 2D Tensor, got 1D.

**Comment by JusperLee** [comment]
你应该把输入加上batch维度

**Comment by PANPANKK** [comment]
谢谢谢谢，将torchaudio版本更新对就不报错了~



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kai Li (李凯) ***@***.***&gt;
发送时间: 2023年1月15日 23:13
收件人: JusperLee/Dual-Path-RNN-Pytorch ***@***.***&gt;
抄送: darcy JJJ ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[JusperLee/Dual-Path-RNN-Pytorch] 关于使用预训练模型的报错 (Issue #52)





 
你应该把输入加上batch维度
