### ISSUE TITLE
How is the performance（rtf） on the CPU or GPU?

### ISSUE THREAD

**Issue by xxoospring** [JusperLee/Dual-Path-RNN-Pytorch#6]

**Comment by JusperLee** [comment]
Because the model is relatively large, I did not use CPU to train the model. The effect of GPU training can achieve the results mentioned in the paper.

**Comment by xxoospring** [comment]
> Because the model is relatively large, I did not use CPU to train the model. The effect of GPU training can achieve the results mentioned in the paper.

I'm sorry, what I said was inference speed, not training

**Comment by JusperLee** [comment]
I only tested the GPU's inference speed: 3.66/s
