### ISSUE TITLE
Don't discard last chunk during training

### ISSUE THREAD

**Issue by jonashaag** [JusperLee/Dual-Path-RNN-Pytorch#7]
Currently the data loader code discards the last chunk if it doesn't exactly fit `N * chunk_size` https://github.com/JusperLee/Dual-Path-RNN-Pytorch/blob/master/data_loader/AudioData.py#L77

For example taking the default step size of 1s and chunk size of 2s and an audio clip of length 3.5s, these are the chunks:

```
start | start + chunk_size
0     | 2 -> ok
1     | 3 -> ok
2     | 4 -> break
```

Is this on purpose? Shouldn't we zero-pad the last chunk?

**Comment by JusperLee** [comment]
My idea is to cut each segment directly for 2s. If more than two seconds, I don’t want padding. Because padding may affect the final result.

**Comment by jonashaag** [comment]
Ok, but that means you'll never see the "ends" of the audio files since they are always skipped.

**Comment by JusperLee** [comment]
是的

**Comment by JusperLee** [comment]
yes, you're right

**Comment by jonashaag** [comment]
Ok :)
